### ISSUE TITLE
Blueshift SDK fails to compile in XCode 14.3

### ISSUE THREAD

**Issue by chrisshiplet** [blueshift-labs/blueshift-react-native#29]
Running into this issue, looks like it's already fixed in the underlying lib, just need to update the dependency on this one: https://github.com/blueshift-labs/Blueshift-iOS-SDK/issues/255

**Comment by ketanshikharebsft** [comment]
Hey @chrisshiplet, Apologies for the inconvenience caused. 
We have released the react native plugin update [v1.0.3 ](https://www.npmjs.com/package/blueshift-react-native) with the fixes. This should resolve the issue.

**Comment by dane-zark** [comment]
Thanks @ketanshikharebsft. We'll give it a go.
