### ISSUE TITLE
Sensitive information stored in device memory

### ISSUE THREAD

**Issue by lukas-cushon** [blueshift-labs/blueshift-react-native#36]
Hi 

I am using "blueshift-react-native": "^1.0.3" in react native project.
After setting user data two files are created in the android device.

```
shared_prefs/com.package.user_info_file.xml
shared_prefs/com.package.BsftEmailPrefFile.xml
```

Above files include user email which is not encrypted and stored in clear text.

My two questions are:

a) Is there a way to encrypt these values in a way the events and SDK will still work?

b) `Blueshift.removeUserInfo()` method description states 

```
	/**
	 * Remove all the saved user info from the SDK.
	 * 
	 * Usage -
	 * Blueshift.removeUserInfo();
	 */
	function removeUserInfo(): void;
```
yet above mention files remain in the phone memory post logout. Is that expected behaviour?

**Comment by rahulrvp** [comment]
Hi @lukas-cushon. The issues reported on GitHub aren't closely monitored.

The primary -- and the correct -- way to report an issue to us is via the customer support channel. Send us an email at [support@blueshift.com](mailto:support@blueshift.com) from your work email with all the necessary details that contain step-by-step instructions on how to reproduce the issue.

In addition, include the following details based on the nature of the issue.

- Crash Log (in case of app crash)
- Screenshots/Screen Recordings
- Device details (Make, OS version etc)
- Blueshift Android/iOS SDK version being used
- Campaign Name/Link (if available)
- Template Name/Link (if available)
- Any extra details that you think would help in repro the issue

Thanks,
Rahul
