### ISSUE TITLE
error: cannot find symbol String while updating to RN 0.73.4

### ISSUE THREAD

**Issue by ayobami303** [blueshift-labs/blueshift-react-native#37]
Hello,

I get an error after updating our app to the latest RN. 

`
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
.../node_modules/blueshift-react-native/android/src/main/java/com/blueshift/reactnative/BlueshiftReactNativeModule.java:440: error: cannot find symbol String errorMessage = getReactApplicationContext().getString(R.string.bsft_inbox_delete_failure_message); ^ symbol: variable string location: class R
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: .../node_modules/blueshift-react-native/android/src/main/java/com/blueshift/reactnative/BlueshiftReactNativeEventHandler.java uses unchecked or unsafe operations.
`

Java version: 17
gradle version: 8.3
blueshift sdk version: 3.4.4

**Comment by rahulrvp** [comment]
Hi @ayobami303. The issues reported on GitHub aren't closely monitored.

The primary -- and the correct -- way to report an issue to us is via the customer support channel. Send us an email at [support@blueshift.com](mailto:support@blueshift.com) from your work email with all the necessary details that contain step-by-step instructions on how to reproduce the issue.

In addition, include the following details based on the nature of the issue.

- Crash Log (in case of app crash)
- Screenshots/Screen Recordings
- Device details (Make, OS version etc)
- Blueshift Android/iOS SDK version being used
- Campaign Name/Link (if available)
- Template Name/Link (if available)
- Any extra details that you think would help in repro the issue

Thanks,
Rahul
